version: '3.1'
services:
  app:
    container_name: app
    image: sidrdetyam/fortytwoback:latest
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/fortytwo
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password

  db:
    image: 'postgres:15.2'
    container_name: db
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=fortytwo